services:
  app:
    build: .
    ports:
      - "8085:80"    # ← Cambia de 8080 a 8085
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: caja_user
      DB_PASSWORD: caja_password
      DB_NAME: ControlCajaAhorro

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ControlCajaAhorro
      MYSQL_USER: caja_user
      MYSQL_PASSWORD: caja_password
    ports:
      - "3308:3306"  # ← Cambia de 3306 a 3308
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: